import mongoose from 'mongoose';

const userIds = [
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
];

export const projects = [
  {
    _id: userIds[0],
    imgsrc: 'https://i.imgur.com/I3P25N1.png',
    title: 'Blog FlexBox',
    text: 'In this project I developed a simple blog using css with flexbox layout modeling, it was an application of a course I studied. The blog is responsive and has the concept of mobile first.',
    view: 'https://megas-mdn.github.io/BlogFlexBox/',
    source: 'https://github.com/Megas-MDN/BlogFlexBox',
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: userIds[1],
    imgsrc: 'https://i.imgur.com/IEtojz2.png',
    title: 'Site Css Grid',
    text: 'Site built with html5 and css3 applying css grid resources with responsiveness and using the concept of mobile first. Project carried out during a course where I could deepen my styling knowledge.',
    view: 'https://megas-mdn.github.io/BlogFlexBox/',
    source: 'https://github.com/Megas-MDN/BlogFlexBox',
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: userIds[2],
    imgsrc: 'https://i.imgur.com/0y5WewD.png',
    title: 'CRUD with React form',
    text: 'Application for creating, reading, updating and deleting information from a form. A simple app using react js with context API, with functional components. Plus a dark mode feature on all routes.',
    view: 'https://crud-react-forms.vercel.app/',
    source: 'https://github.com/Megas-MDN/crud-react-forms',
    createdAt: 1288090662,
    updatedAt: 1288090662,
    __v: 0,
  },
  {
    _id: userIds[3],
    imgsrc: 'https://i.imgur.com/J73PumF.png',
    title: 'MegTunes request API',
    text: "Playsongs application that consumes an itunes API and returns a list of songs, this application requires a user with validation, it also allows you to edit your profile, save songs in favorites and customize the user's avatar.",
    view: 'https://meg-tunes.vercel.app/',
    source: 'https://github.com/Megas-MDN/megTunes',
    createdAt: 1219214568,
    updatedAt: 1219214568,
    __v: 0,
  },
  {
    _id: userIds[4],
    imgsrc: 'https://i.imgur.com/pED86dA.png',
    title: 'Online Store',
    text: 'In this project a simplified version of an online store was created, users will be able to search for products by terms and categories in the Mercado Livre API, add and remove them from a shopping cart, view details and previous evaluations of a product, in addition to creating new evaluations.',
    view: 'https://online-store-iota.vercel.app/',
    source: 'https://github.com/Megas-MDN/online-store',
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: userIds[5],
    imgsrc: 'https://i.imgur.com/L33vYne.png',
    title: 'Game quiz',
    text: 'This is a question and answer game based on the Trivia game using React and Redux, some features of this app are: log in to the game, and in the game you have to choose one of the available answers, it is also possible configure some game options, difficulty level and amount of questions.',
    view: 'https://game-quiz-beta.vercel.app/',
    source: 'https://github.com/Megas-MDN/game-quiz',
    createdAt: 1381326073,
    updatedAt: 1381326073,
    __v: 0,
  },
  {
    _id: userIds[6],
    imgsrc: 'https://i.imgur.com/4Mb3uFz.png',
    title: 'Portfolio',
    text: 'Portfolio made with react and context api, prepared to receive the cards by an external api, something that will still be implemented. This is made with lots of love and care. In this portfolio I show some showcases that I developed and have been creating in my developer career.',
    view: 'https://megas-mdn.github.io/my-portifolio/',
    source: 'https://github.com/Megas-MDN/my-portifolio',
    createdAt: 1714704324,
    updatedAt: 1642716557,
    __v: 0,
  },
  {
    _id: userIds[7],
    imgsrc: 'https://i.imgur.com/DiIMLUg.png',
    title: 'NetFlix Clone',
    text: 'In this project I built a netflix clone using the tmdb api to make the data requests, I also used custom hooks to avoid repeating the same codes and finally the deploy was performed on the firebase hosting. The project allows the user to watch the trailers of each movie by clicking on the cards.',
    view: 'https://megaflix-4c4e7.web.app/',
    source: 'https://github.com/Megas-MDN/Netflix-Clone',
    createdAt: 1369908044,
    updatedAt: 1359322268,
    __v: 0,
  },
  {
    _id: userIds[8],
    imgsrc: 'https://i.imgur.com/5lOKxdw.png',
    title: 'API to portifolio',
    text: 'Using node js rules along with express, I made a simple API to upload my projects, without the need to deploy all the time. The search is automatic directly from the endpoint.',
    view: 'https://api-data-portfolio.onrender.com/projects',
    source: 'https://github.com/Megas-MDN/apiDataPortfolio',
    createdAt: 1379998094,
    updatedAt: 1389392968,
    __v: 0,
  },
];
